version: '3.7'
services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_ORG: ${OPENAI_ORG}
    #volumes:
    #  - ./:/app